Repository hatchways/team-beluga, pull requests merged in 2021-03, with the labels that each got.

#23 Adding home page skeleton and navbar
  .gitignore
  client/package-lock.json
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/components/Header.js
  client/src/images/logo.png
  client/src/pages/Home.js
  client/src/themes/theme.js
  server/.env
Labels: Frontend

#29 Adding event types controller
  Pipfile
  Pipfile.lock
  server/api/eventType_handler.py
  server/api/google_login_handler.py
  server/api/google_signup_handler.py
  server/app.py
  server/config.py
  server/model/model.py
Labels: Backend

#34 Adding frontend onboarding pages
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/DropdownSelect.js
  client/src/components/Onboarding.js
  client/src/pages/CalendarConfirm.js
  client/src/pages/Home.js
  client/src/pages/ProfileSetting.js
  client/src/pages/UserAvailability.js
  client/src/themes/theme.js
Labels: Frontend

#37 Set Up SendGrid
  server/Pipfile
  server/Pipfile.lock
  server/config.py
  server/service/email_service.py
Labels: Backend

#36 Integration of creating, loading eventTypes & copying link
  client/package.json
  client/src/App.js
  client/src/components/EventTypeDialog.js
  client/src/components/EventTypesTab.js
  client/src/components/Header.js
  client/src/components/LoginComponents.js
  client/src/globals/UserContext.js
  client/src/images/7f21cd746f9cd939e52f7d98d746700660f6d580.png
  client/src/pages/Home.js
  client/src/pages/Login.js
  client/src/pages/SignUp.js
  client/src/themes/theme.js
  client/yarn.lock
  server/api/eventType_handler.py
  server/api/google_login_handler.py
  server/api/google_signup_handler.py
Labels: Integration

#42 Task/#18 in onboarding
  client/src/components/Onboarding.js
  client/src/pages/ProfileSetting.js
  client/yarn.lock
  server/api/url_check_handler.py
  server/migrations/versions/1b22871f9fdd_.py
  server/migrations/versions/2d9674302693_.py
  server/migrations/versions/348288297ea5_.py
  server/migrations/versions/39346b06ca58_.py
  server/migrations/versions/5ac3ac59da92_.py
  server/migrations/versions/a016ef053c2f_.py
  server/migrations/versions/dcd6bf90baeb_.py
  server/migrations/versions/f60a03e39f0b_.py
  server/model/model.py
Labels: Integration

#45 Setup Stripe BE API with FE framework
  client/package.json
  client/src/App.js
  client/src/components/CardSection.js
  client/src/components/CheckoutForm.js
  client/src/pages/StripeCheckout.js
  client/yarn.lock
  server/Pipfile
  server/Pipfile.lock
  server/api/subscribe_handler.py
  server/app.py
  server/config.py
Labels: Integration

#59 Refactoring onboarding steps
  client/src/App.js
  client/src/components/onboarding/CalendarConfirm.js
  client/src/components/onboarding/ProfileSetting.js
  client/src/components/onboarding/UserAvailability.js
  client/src/pages/CalendarConfirm.js
  client/src/pages/Login.js
  client/src/pages/Onboarding.js
  client/src/pages/ProfileSetting.js
  client/src/pages/SignUp.js
Labels: Frontend

#58 Add auth decorator
  server/api/availability_handler.py
  server/api/eventType_handler.py
  server/api/subscribe_handler.py
  server/api/url_check_handler.py
  server/api/user_info_handler.py
  server/utils/auth/middleware.py
Labels: Backend

#55 Adding alert context
  client/package.json
  client/src/App.js
  client/src/components/EventTypeDialog.js
  client/src/components/EventTypesTab.js
  client/src/components/FlashAlert.js
  client/src/components/Header.js
  client/src/components/onboarding/ProfileSetting.js
  client/src/components/onboarding/UserAvailability.js
  client/src/globals/AlertContext.js
  client/src/pages/Login.js
  client/src/pages/Onboarding.js
  client/src/pages/SignUp.js
  client/yarn.lock
Labels: Frontend

#65 Add appointment controllers
  server/api/apointment_handler.py
  server/api/google_login_handler.py
  server/app.py
  server/model/model.py
  server/utils/auth/google_client.py
Labels: Backend

#80 Integration of cancel appointment
  client/src/components/ScheduledEventsTable.js
  server/api/appointment_handler.py
  server/app.py
  server/migrations/versions/23872f10cbfd_.py
  server/model/model.py
  server/utils/auth/google_client.py
Labels: Fullstack
